[package]
name = "rskeyvi"
version = "0.1.0"
build = "build.rs"
authors = ["Subu <subu@cliqz.com>"]

[build-dependencies]
bindgen = "0.30.0"
cmake = "*"

[dependencies]
serde_json = "1.0"
rayon = "0.8.2"
rand = "0.3"

